### ISSUE TITLE
CW0001/T0001.2 - Design the market UI ( Priority-1 )

### ISSUE THREAD

**Issue by codewarriors0005** [CodeWarriorsOrganization/CodeWarriorsFinalYearProject#31]
### User Story :

> AS a player,I NEED the stock market to be formed of set of companies that are organised into market sectors such as Finance, Technology, Consumer Services, Manufacturing, SO THAT I will be able to view the sector of a company, what are the trends to make a decision on what sector to invest.

### **Task :**

> **Design the market UI**

**Comment by codewarriors0002** [comment]
I designed StockMarketGameScreen. Please check it.
![1527933587424](https://user-images.githubusercontent.com/39667518/40873511-e852edf8-667e-11e8-944d-c00db7f18bc8.JPEG)
