### ISSUE TITLE
CW0001/T0001.3 - Implement  Client Side Logic ( Priority-1 ) 

### ISSUE THREAD

**Issue by codewarriors0005** [CodeWarriorsOrganization/CodeWarriorsFinalYearProject#32]
### User Story :

> AS a player,I NEED the stock market to be formed of set of companies that are organised into market sectors such as Finance, Technology, Consumer Services, Manufacturing, SO THAT I will be able to view the sector of a company, what are the trends to make a decision on what sector to invest.

### Task :
> **Implement the server & client side logic**

**Comment by codewarriors0002** [comment]
I implement the rest service for giving stock details to player. in this state i give only dummy value. stock price generate part is not implement.  
That response came like that:-

{
    "gameTime": 60,
    "turnTime": 6,
    "companies": [
        {
            "companyName": "aaaa",
            "sectorName": "financial",
            "turns": [
                {
                    "turnId": 1,
                    "price": 101
                },
                {
                    "turnId": 2,
                    "price": 102
                },
                {
                    "turnId": 3,
                    "price": 103
                }
            ]
        },
        {
            "companyName": "bbbb",
            "sectorName": "financial",
            "turns": [
                {
                    "turnId": 1,
                    "price": 101
                },
                {
                    "turnId": 2,
                    "price": 102
                },
                {
                    "turnId": 3,
                    "price": 103
                }
            ]
        }
    ]
}

**Comment by codewarriors0005** [comment]
Done.

**Comment by codewarriors0005** [comment]
Task T0016.3 and T0016.4 of User Story CW0016 is committed through this task.
