### ISSUE TITLE
CW0001/T0001.1 - Research on Sectors , Companies and Trends ( Priority-1 )

### ISSUE THREAD

**Issue by codewarriors0005** [CodeWarriorsOrganization/CodeWarriorsFinalYearProject#6]
### User Story :

> AS a player,I NEED the stock market to be formed of set of companies that are organised into market sectors such as Finance, Technology, Consumer Services, Manufacturing, SO THAT I will be able to view the sector of a company, what are the trends to make a decision on what sector to invest.

### Task :

> **Research about sectors,companies,trends to be included.**

**Comment by codewarriors0002** [comment]
I Suggest 4 sectors and 12 companies for buy and sell in stock market.
![1527938603784](https://user-images.githubusercontent.com/39667518/40874156-6a8e4c9a-6689-11e8-9d5f-e713def187f2.JPEG)
